apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login
  name: login
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - image:  quay.io/oktaysavdi/login #Code Repo https://github.com/OktaySavdi/login_example
        imagePullPolicy: IfNotPresent
        name: login
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: login
  name: login
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: login
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: login-ingress
spec:
  rules:
  - host: login.10.10.10.10.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: login
          servicePort: 80
